# Generated by Django 5.2 on 2025-08-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='capacidad_usuarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='intensidad',
            field=models.CharField(choices=[('baja', 'BAJA'), ('media', 'MEDIA'), ('alta', 'ALTA')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='velocidad',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
