# Generated by Django 5.2 on 2025-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosmodelo',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='usuariosmodelo',
            name='provincia',
            field=models.CharField(choices=[('alajuela', 'ALAJUELA'), ('cartago', 'CARTAGO'), ('heredia', 'HEREDIA'), ('san josé', 'SAN JOSÉ'), ('limón', 'LIMÓN'), ('guanacaste', 'GUANACASTE'), ('puntarenas', 'PUNTARENAS')], default='san jose', max_length=100),
            preserve_default=False,
        ),
    ]
