# Generated by Django 5.2 on 2025-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ubicaciones_capacidad_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='compania',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='capacidad_usuarios',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
