# Generated by Django 5.2 on 2025-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuariosmodelo_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='reporte',
            field=models.IntegerField(default=0),
        ),
    ]
