# Generated by Django 5.2 on 2025-05-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_crearubicacion_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
