# Generated by Django 5.2 on 2025-05-31 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='latitud',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='longitud',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
