# Generated by Django 5.2 on 2025-06-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ubicaciones_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmodelo',
            name='banner',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usuariosmodelo',
            name='img',
            field=models.CharField(default='', max_length=300),
        ),
    ]
