# Generated by Django 5.2 on 2025-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuariosmodelo_banner_usuariosmodelo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_anuncio', models.TextField()),
                ('hora_anuncio', models.TimeField(auto_now_add=True)),
                ('fecha_anuncio', models.DateField(auto_now_add=True)),
                ('gravedad_anuncio', models.CharField(choices=[('leve', 'LEVE'), ('grave', 'GRAVE'), ('muy grave', 'MUY GRAVE')], max_length=50)),
            ],
        ),
    ]
